app:
  development:
    mysql:
      host: aws-1-ap-northeast-1.pooler.supabase.com
      port: 6543
      database: postgres
      password: xya0526.
      username: postgres.gbmigijigqsnqzefifxi
      type: postgres
    redis: 
      host: 'r-bp1xxxhoqghu5ly8japd.redis.rds.aliyuncs.com'
      port: 6379  # 新增：拆分后的用户名
      password: "r-bp1xxxhoqghu5ly8ja:Xya0526+"   
      db: 0
      
  production:
    mysql:
      host: aws-1-ap-northeast-1.pooler.supabase.com
      port: 6543
      database: postgres
      password: xya0526.
      username: postgres.gbmigijigqsnqzefifxi
      type: postgres
    redis:
      host: 'r-bp1xxxhoqghu5ly8japd.redis.rds.aliyuncs.com'
      port: 6379  # 新增：拆分后的用户名
      password: "r-bp1xxxhoqghu5ly8ja:Xya0526+"  
      db: 0